modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/NoSignGUI/issues"
license = "MIT"

[[mods]]
modId = "drsr"
version = "2.0.0"
displayName = "Dynamic Raid Spawn Radius"
authors = "CoolAid48"

credits = "Mod icon by pandalexi12"

description = '''
Allows changing the spawn radius of raid waves in-game via a simple config!
'''
logoFile = 'assets/drsr/icon.png'

[[mixins]]
config = "drsr.mixins.json"
