modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "drsr"
version = "${version}"
displayName = "Dynamic Raid Spawn Radius"
authors = "CoolAid48"
description = '''

'''
#logoFile = ""

[[dependencies.drsr]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drsr]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "drsr.mixins.json"
